prow_ignored:
- &config-sync-terraform-job-spec
  nodeSelector:
    # This job requires 8vCPUs or less, so it is "small".
    kpt-config-sync/type: presubmit
    kpt-config-sync/size: small
- &config-sync-terraform-job
  cluster: build-kpt-config-sync
  decorate: true
- &config-sync-terraform-container
  image: gcr.io/k8s-testimages/gcloud-terraform:v20220913-3bc71e6c7a
  command:
  - make
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
presubmits:
  GoogleContainerTools/config-sync:
  - <<: *config-sync-terraform-job
    name: kpt-config-sync-terraform-presubmit
    run_if_changed: "^e2e/testinfra/terraform/"
    spec:
      <<: *config-sync-terraform-job-spec
      containers:
      - <<: *config-sync-terraform-container
        args:
        - -C
        - e2e/testinfra/terraform
        - validate
